### ISSUE TITLE
Create a Search bar feature in the nav bar.

### ISSUE THREAD

**Issue by ErickNavaP** [Christy131/Wow-Project-ReEntry101#43]
## Overview
We need to create a search function that will allow the user to search for relevant key words that might have been posted previously on the site. For example, a user could type in the word "housing" and anything on the site should come up.

**Comment by MikaylaMunn** [comment]
This is done for all the pages minus the resource, it would be helpful if someone could create a database for the resouces page @ErickNavaP or @Christy131, if you want to do that that would be great.
