### ISSUE TITLE
Create Models

### ISSUE THREAD

**Issue by Christy131** [Christy131/Wow-Project-ReEntry101#5]
## Overview

Model field reference _ Django documentation _ Django.html

## Technical Notes

[](https://docs.djangoproject.com/en/4.1/ref/models/)

**Comment by jtc21am** [comment]
Are the models being created by Christy exclusively? Consider adding other collaborators under the Assignees section.

https://docs.djangoproject.com/en/4.1/ref/models/fields/

**Comment by Christy131** [comment]
I will add Erick and Mikayla, we plan to do as much jointly as possible.
